Added cast to prevent compile error
Compilation was failing otherwise due to the different type.

```
/archive/shared/projects/blocks/src/world.c: In function ‘loop’:
/archive/shared/projects/blocks/src/world.c:86:48: error: passing argument 4 of ‘terrain_neighbors2’ from incompatible pointer type [-Wincompatible-pointer-types]
   86 |             terrain_neighbors2(&terrain, x, z, neighbors);
      |                                                ^~~~~~~~~
      |                                                |
      |                                                const chunk_t **
```